const stateMap = new Map([
    ['Andhra Pradesh', 'AD'],
    ['Arunachal Pradesh', 'AR'],
    ['Assam', 'AS'],
    ['Bihar', 'BR'],
    ['Chattisgarh', 'CG'],
    ['Delhi', 'DL'],
    ['Goa', 'GA'],
    ['Gujarat', 'GJ'],
    ['Haryana', 'HR'],
    ['Himachal Pradesh', 'HP'],
    ['Jammu and Kashmir', 'JK'],
    ['Jharkhand', 'JH'],
    ['Karnataka', 'KA'],
    ['Kerela', 'KL'],
    ['Lakshadweep', 'LD'],
    ['Madhya Pradesh', 'MP'],
    ['Maharashtra', 'MH'],
    ['Manipur', 'MN'],
    ['Meghalaya', 'ML'],
    ['Mizoram', 'MZ'],
    ['Nagaland', 'NL'],
    ['Odisha', 'OR'],
    ['Pondicherry', 'PY'],
    ['Punjab', 'PB'],
    ['Rajasthan', 'RJ'],
    ['Sikkim', 'SK'],
    ['Tamil Nadu', 'TN'],
    ['Telangana', 'TS'],
    ['Tripura', 'TR'],
    ['Uttar Pradesh', 'UP'],
    ['West Bengal', 'WB'],

    ['Andaman and Nicobar Islands', 'AN'],
    ['Chandigarh', 'CH'],
    ['Dadra & Nagar Haveli and Daman & Diu', 'DNHDD'],
    ['Ladakh', 'LA'],
    ['Other Territory', 'OT'],
])

//Trial Purpose Only
const ipcSections = new Map([
    ["34", 40],
    ["120A",80],
    ["120B", 50],
    ["125",90],
    ["143",85],
    ["146",60],
    ["153A",60],
    ["160",40],
    ["186",70],
    ["192",20],
    ["193",60],
    ["195",60],
    ["272",50],
    ["290",65],
    ["294A",80],
    ["420", 50],
    ["500", 20],
    ["506", 20],
    ["506B", 20],
    ["323", 10],
    ["354", 35],
    ["394", 35],
    ["427", 30],
    ["377", 50],
    ["468", 60],
    ["471", 60],
    ["376", 70],
    ["307", 80],
    ["489A", 80],
    ["479", 50],
    ["304", 95],
    ["376A", 85],
    ["302", 100],
    ["305",75]
    ["306",40],
    ["323",65],
    ["363",60],
    ["380",50],
    ["406",70],
    ["409",70],
    ["415",70],
    ["427",60],
    ["441",55],
    ["452",70],
    ["465",65],
    ["468",35],
    ["489A",55],
    ["499",75],
    ["500",80],
    ["510",80],
    ["POSCO",100]
    
    
    ])
    
// Track mapping
const trackMap = new Map([
    ['Matters relating to maintenance', 1],
    ['Matters relating to guardianship or custody of children', 1],
    ['Matters relating to adoption', 1],
    ['Matters relating to visitation rights', 1],
    ['Matters relating to the grant of Letter of Administration, Probate and Succession Certificate', 1],
    ['Original Proceedings and appeals under the Kerala Buildings (Lease and Rent Control) Act, 1965 (Act 2 of 1965)', 1],
    ['All Civil Miscellaneous appeals', 1],
    ['Suits for money', 1],
    ['Proceedings under the Mental Health Act,1987 (Central Act 14 of 1987)', 1],
    ['Proceedings for transfer of matters pending before Civil Courts', 1],
    ['All summary suits', 1],

    ['Matters relating to matrimonial disputes not falling under track I', 2],
    ['Suits for eviction', 2],
    ['Suits for injunction', 2],
    ['Claim petitions under the Motor Vehicles Act, 1988 (Central Act 59 of 1988)', 2],
    ['Land Acquisition references and petitions for compensation relating to property under other different legislations like Telegraph Act, 1885 (Central Act 13 of 1885), Petroleum Act, 1934 (Central Act 30 of 1934) etc', 2],
    ['Proceedings under the Arbitration and Conciliation Act, 1996 (Central Act 26 of 1996)', 2],
    ['Suits under the Fatal Accident Act, 1855', 2],
    ['Suits and other proceedings relating to Intellectual Property Rights', 2],

    ['Suits for partition', 3],
    ['Suits for declaratory relief', 3],
    ['Suits for specific performance', 3],
    ['Suits for possession', 3],
    ['All appeals other than Civil Miscellaneous Appeals and appeals under the Kerala Buildings (Lease and Rent Control) Act, 1965 (Act 2 of 1965)', 3],
    ['Suits for damages', 3],
    ['Suits relating to easement rights', 3],
    ['Suits and other proceedings relating to trust property', 3],
    ['Proceedings under the Insolvency Act, 1955 (Act 2 of 1956)', 3],
    ['Suits for accounts', 3],
    ['Matters relating to execution', 3],
    ['Such other cases not included elsewhere', 3],
])

// case type mapping

const caseTypeMap = new Map([
    ['', ''],
    ['', ''],
    ['', ''],
    ['', ''],
    ['', ''],
    ['', ''],
    ['', ''],
    ['', ''],
    ['', ''],
    ['', ''],
])

module.exports = {stateMap, ipcSectionMap, trackMap}
