const stateMap = new Map([
    ['Andhra Pradesh', 'AD'],
    ['Arunachal Pradesh', 'AR'],
    ['Assam', 'AS'],
    ['Bihar', 'BR'],
    ['Chattisgarh', 'CG'],
    ['Delhi', 'DL'],
    ['Goa', 'GA'],
    ['Gujarat', 'GJ'],
    ['Haryana', 'HR'],
    ['Himachal Pradesh', 'HP'],
    ['Jammu and Kashmir', 'JK'],
    ['Jharkhand', 'JH'],
    ['Karnataka', 'KA'],
    ['Kerela', 'KL'],
    ['Lakshadweep', 'LD'],
    ['Madhya Pradesh', 'MP'],
    ['Maharashtra', 'MH'],
    ['Manipur', 'MN'],
    ['Meghalaya', 'ML'],
    ['Mizoram', 'MZ'],
    ['Nagaland', 'NL'],
    ['Odisha', 'OR'],
    ['Pondicherry', 'PY'],
    ['Punjab', 'PB'],
    ['Rajasthan', 'RJ'],
    ['Sikkim', 'SK'],
    ['Tamil Nadu', 'TN'],
    ['Telangana', 'TS'],
    ['Tripura', 'TR'],
    ['Uttar Pradesh', 'UP'],
    ['West Bengal', 'WB'],

    ['Andaman and Nicobar Islands', 'AN'],
    ['Chandigarh', 'CH'],
    ['Dadra & Nagar Haveli and Daman & Diu', 'DNHDD'],
    ['Ladakh', 'LA'],
    ['Other Territory', 'OT'],
])

//Trial Purpose Only
// const ipcSectionMap = new Map([
//     ["Section 302",100],
//     ["Section 304",95],
//     ["Section 420",50],
//     ["Section 489A",80],
//     ["Section 34",40],
//     ["Section 354",35],
//     ["Section 509",40],
//     ["Section 138",20],
//     ["Section 120B",50],
//     ["Section 307",80],
//     ["Section 376",70],
//     ["Section 468",60],
//     ["Section 471",60],
//     ["Section 479",50],
//     ["Section 506",20],
//     ["Section 500",20],
//     ["Section 376A",85],
//     ["Section 323",10],
//     ["Section 377",50],
//     ["Section 427",30],
//     ["Section 394",35],
//     ["Section 506B",20],
//     // ["Section 323",10],
// ])

const ipcSectionMap = new Map([
    ["Section 34", 40],
    ["Section 120A", 80],
    ["Section 120B", 50],
    ["Section 125", 90],
    ["Section 143", 85],
    ["Section 146", 60],
    ["Section 153A", 60],
    ["Section 160", 40],
    ["Section 186", 70],
    ["Section 192", 20],
    ["Section 193", 60],
    ["Section 195", 60],
    ["Section 272", 50],
    ["Section 290", 65],
    ["Section 294A", 80],
    ["Section 420", 50],
    ["Section 500", 20],
    ["Section 506", 20],
    ["Section 506B", 20],
    ["Section 323", 10],
    ["Section 354", 35],
    ["Section 394", 35],
    ["Section 427", 30],
    ["Section 377", 50],
    ["Section 468", 60],
    ["Section 471", 60],
    ["Section 376", 70],
    ["Section 307", 80],
    ["Section 489A", 80],
    ["Section 479", 50],
    ["Section 304", 95],
    ["Section 376A", 85],
    ["Section 302", 100],
    ["Section 305", 75],
    ["Section 306", 40],
    ["Section 323", 65],
    ["Section 363", 60],
    ["Section 380", 50],
    ["Section 406", 70],
    ["Section 409", 70],
    ["Section 415", 70],
    ["Section 427", 60],
    ["Section 441", 55],
    ["Section 452", 70],
    ["Section 465", 65],
    ["Section 468", 35],
    ["Section 489A", 55],
    ["Section 499", 75],
    ["Section 500", 80],
    ["Section 510", 80],
]);
// Track mapping

const trackMap = new Map([
    ['Matters relating to maintenance', 1],
    ['Matters relating to guardianship or custody of children', 1],
    ['Matters relating to adoption', 1],
    ['Matters relating to visitation rights', 1],
    ['Matters relating to the grant of Letter of Administration, Probate and Succession Certificate', 1],
    ['Original Proceedings and appeals under the Kerala Buildings (Lease and Rent Control) Act, 1965 (Act 2 of 1965)', 1],
    ['All Civil Miscellaneous appeals', 1],
    ['Suits for money', 1],
    ['Proceedings under the Mental Health Act,1987 (Central Act 14 of 1987)', 1],
    ['Proceedings for transfer of matters pending before Civil Courts', 1],
    ['All summary suits', 1],

    ['Matters relating to matrimonial disputes not falling under track I', 2],
    ['Suits for eviction', 2],
    ['Suits for injunction', 2],
    ['Claim petitions under the Motor Vehicles Act, 1988 (Central Act 59 of 1988)', 2],
    ['Land Acquisition references and petitions for compensation relating to property under other different legislations like Telegraph Act, 1885 (Central Act 13 of 1885), Petroleum Act, 1934 (Central Act 30 of 1934) etc', 2],
    ['Proceedings under the Arbitration and Conciliation Act, 1996 (Central Act 26 of 1996)', 2],
    ['Suits under the Fatal Accident Act, 1855', 2],
    ['Suits and other proceedings relating to Intellectual Property Rights', 2],

    ['Suits for partition', 3],
    ['Suits for declaratory relief', 3],
    ['Suits for specific performance', 3],
    ['Suits for possession', 3],
    ['All appeals other than Civil Miscellaneous Appeals and appeals under the Kerala Buildings (Lease and Rent Control) Act, 1965 (Act 2 of 1965)', 3],
    ['Suits for damages', 3],
    ['Suits relating to easement rights', 3],
    ['Suits and other proceedings relating to trust property', 3],
    ['Proceedings under the Insolvency Act, 1955 (Act 2 of 1956)', 3],
    ['Suits for accounts', 3],
    ['Matters relating to execution', 3],
    ['Such other cases not included elsewhere', 3],
])

// case stage mapping

const caseStageMap = new Map([
    ['Return of summons or notice', 10],
    ['Filing of objection or counter affidavit to the interlocutory applications', 20],
    ['Hearing of interlocutory applications', 30],
    ['Filing of written statement or objections', 40],
    ['Consideration of alternative Dispute Resolution mechanisms', 50],
    ['Framing of issues in case of suits', 60],
    ['Pre-trial steps', 70],
    ['Evidence: Examination in chief, cross examination and re-examination', 80],
    ['Arguments', 90],
    ['Judgment', 100]
])

module.exports = {stateMap, ipcSectionMap, trackMap, caseStageMap}





