const stateMap = new Map([
    ['Andhra Pradesh', 'AD'],
    ['Arunachal Pradesh', 'AR'],
    ['Assam', 'AS'],
    ['Bihar', 'BR'],
    ['Chattisgarh', 'CG'],
    ['Delhi', 'DL'],
    ['Goa', 'GA'],
    ['Gujarat', 'GJ'],
    ['Haryana', 'HR'],
    ['Himachal Pradesh', 'HP'],
    ['Jammu and Kashmir', 'JK'],
    ['Jharkhand', 'JH'],
    ['Karnataka', 'KA'],
    ['Kerela', 'KL'],
    ['Lakshadweep', 'LD'],
    ['Madhya Pradesh', 'MP'],
    ['Maharashtra', 'MH'],
    ['Manipur', 'MN'],
    ['Meghalaya', 'ML'],
    ['Mizoram', 'MZ'],
    ['Nagaland', 'NL'],
    ['Odisha', 'OR'],
    ['Pondicherry', 'PY'],
    ['Punjab', 'PB'],
    ['Rajasthan', 'RJ'],
    ['Sikkim', 'SK'],
    ['Tamil Nadu', 'TN'],
    ['Telangana', 'TS'],
    ['Tripura', 'TR'],
    ['Uttar Pradesh', 'UP'],
    ['West Bengal', 'WB'],

    ['Andaman and Nicobar Islands', 'AN'],
    ['Chandigarh', 'CH'],
    ['Dadra & Nagar Haveli and Daman & Diu', 'DNHDD'],
    ['Ladakh', 'LA'],
    ['Other Territory', 'OT'],
])

//Trial Purpose Only
const ipcSections = new Map([
    ["302",100],
    ["304",95],
    ["420",50],
    ["489A",80],
    ["34",40],
    ["354",35],
    ["509",40],
    ["138",20],
    ["120B",50],
    ["307",80],
    ["376",70],
    ["468",60],
    ["471",60],
    ["479",50],
    ["506",20],
    ["500",20],
    ["376A",85],
    ["323",10],
    ["377",50],
    ["427",30],
    ["394",35],
    ["506B",20],
    // ["323",10],
])

module.exports = {stateMap,ipcSections}
